### ISSUE TITLE
The for loop of optimizer.step() and loss.backward(retain_graph=True)

### ISSUE THREAD

**Issue by WithChameleon** [sjames40/Aseq_DIP#1]
Traceback (most recent call last):
  File "F:\Aseq_DIP-main\denoising_main.py", line 167, in <module>
    loss.backward(retain_graph=True)
  File "C:\Users\admin\anaconda3\envs\Hyperspectral\Lib\site-packages\torch\tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\admin\anaconda3\envs\Hyperspectral\Lib\site-packages\torch\autograd\__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3, 64, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

This is the problem when i run the author's denoising code.
Is there some problem with the order of optimizer.step() and loss.backward(retain_graph=True), when I try to remove the for loop in the optimizer and switch the order of the two, the program works fine, is this in line with the original paper in Neural IPS?

**Comment by aia39** [comment]
Did you find any solution to it? I am also facing the same issue.

**Comment by WithChameleon** [comment]
Sorry, i just noticed this e-mail. I tyr to remove the optimizer loop and change the order between the&nbsp;optimizer.step() and loss.backward(retain_graph=True), the code works.
The part revised code is as follows:


 for epoch in range(5000):
    optimizer.zero_grad()
    out = net(net_input)
    loss_input = mse(net_input, out)
    loss = mse(out, img_noisy_torch) + 1 * loss_input
    # for i in range(2):
    #     optimizer.step()
    #     loss.backward(retain_graph=True)

    loss.backward(retain_graph=True)
    optimizer.step()

    net_input = img_noisy_torch - 1 * (out.detach() - img_noisy_torch)
    with torch.no_grad():
        psnr = compare_psnr(np.array(img_var.cpu()), np.array(out.cpu()))
        psnrs.append(psnr)
        print(psnr)

        losses.append(loss.item())
My new e-mail address is ***@***.***"


Regards,
Liu Pan.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sjames40/Aseq_DIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年5月28日(星期三) 凌晨3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sjames40/Aseq_DIP] The for loop of optimizer.step() and loss.backward(retain_graph=True) (Issue #1)



aia39 left a comment (sjames40/Aseq_DIP#1)
 
Did you find any solution of it? I am also facing the same issue?

**Comment by aia39** [comment]
> Sorry, i just noticed this e-mail. I tyr to remove the optimizer loop and change the order between the&nbsp;optimizer.step() and loss.backward(retain_graph=True), the code works.
> The part revised code is as follows:
> 
> 
>  for epoch in range(5000):
>     optimizer.zero_grad()
>     out = net(net_input)
>     loss_input = mse(net_input, out)
>     loss = mse(out, img_noisy_torch) + 1 * loss_input
>     # for i in range(2):
>     #     optimizer.step()
>     #     loss.backward(retain_graph=True)
> 
>     loss.backward(retain_graph=True)
>     optimizer.step()
> 
>     net_input = img_noisy_torch - 1 * (out.detach() - img_noisy_torch)
>     with torch.no_grad():
>         psnr = compare_psnr(np.array(img_var.cpu()), np.array(out.cpu()))
>         psnrs.append(psnr)
>         print(psnr)
> 
>         losses.append(loss.item())
> My new e-mail address is ***@***.***"
> 
> 
> Regards,
> Liu Pan.
> […](#)

Thank you for the suggestion. If you remove the for loop, then how will it do the sequential training that aSeqDIP is supposed to do?

**Comment by WithChameleon** [comment]
As you said, I just make the code work, but not corresponding to the paper settings.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sjames40/Aseq_DIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年7月7日(星期一) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sjames40/Aseq_DIP] The for loop of optimizer.step() and loss.backward(retain_graph=True) (Issue #1)



aia39 left a comment (sjames40/Aseq_DIP#1)
  
Sorry, i just noticed this e-mail. I tyr to remove the optimizer loop and change the order between the&nbsp;optimizer.step() and loss.backward(retain_graph=True), the code works.
 The part revised code is as follows:
 
for epoch in range(5000):
 optimizer.zero_grad()
 out = net(net_input)
 loss_input = mse(net_input, out)
 loss = mse(out, img_noisy_torch) + 1 * loss_input
 # for i in range(2):
 #     optimizer.step()
 #     loss.backward(retain_graph=True)
 loss.backward(retain_graph=True) optimizer.step() net_input = img_noisy_torch - 1 * (out.detach() - img_noisy_torch) with torch.no_grad():     psnr = compare_psnr(np.array(img_var.cpu()), np.array(out.cpu()))     psnrs.append(psnr)     print(psnr)     losses.append(loss.item())  
My new e-mail address is @.***"
 
Regards,
 Liu Pan.
 …
  
Thank you for the suggestion. If you remove the for loop, then how will it do the sequential training that aSeqDIP is supposed to do?
